name: Terraform Apply Dev

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (e.g., dev)'
        required: true
        default: 'dev'
      action:
        description: 'Terraform action to perform (apply/destroy)'
        required: true
        default: 'apply'
      session_id:
        description: 'Chatbot session ID'
        required: false
      description:
        description: 'User input or context'
        required: false

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize Terraform
        run: echo "Hello World"

      - name: Output Session Info
        run: |
          echo "Session ID: ${{ github.event.inputs.session_id }}"
          echo "User Description: ${{ github.event.inputs.description }}"
